spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
   url: jdbc:h2:mem:database
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
    cores:
      allowed-methods: true
      allowed-headers: true
      allowed-origins: true


